CREATE TABLE IF NOT EXISTS color_charts (
    product_id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    part VARCHAR(256) NOT NULL,
    maker VARCHAR(256) NOT NULL,
    red INTEGER NOT NULL,
    green INTEGER NOT NULL,
    blue INTEGER NOT NULL,
    coat INTEGER NOT NULL,
    ratio INTEGER NOT NULL
);
